### ISSUE TITLE
verschilplots

### ISSUE THREAD

**Issue by wzuidema** [martijnvanbeers/nlp-attribution-notebooks#6]
In zowel de k-value notebook als de weighted average squared distance notebook: graag de functionaliteit toevoegen dat de gebruiker twee stukjes tekst kan selecteren en aan het einde een 'verschil-plot' krijgt, die visualiseert hoezeer de attention-heads verschillen bij verschillende input.

**Comment by martijnvanbeers** [comment]
finished in 768cf63bcf10d3b41ef11e56f2be360a5075a483
